### ISSUE TITLE
LCSC part numbers?

### ISSUE THREAD

**Issue by 8waysanta** [eflukx/OpalSCSI#2]
Hi, I was wondering if you could direct me to the LCSC part numbers you used for the Micro SD card holder and the Micro USB connector, many thanks.

**Comment by eflukx** [comment]
The SD card reader is pretty _Chinese generic_ 🇨🇳 😸 and can be found from various sources and vendors..

From LCSC the "XUNPU TF-115" [(LCSC# C266620)](https://www.lcsc.com/product-detail/SD-Card-Connectors_XUNPU-TF-115_C266620.html) will fit, as well as the "SOFNG TF-015" [(LCSC# C113206)](https://www.lcsc.com/product-detail/Connector-Card-Sockets_SOFNG-TF-015_C113206.html)

The MicroUSB connector is pretty generic as well (probably even moreso:)) and a lot of different types will fit just fine, for instance this one: [LCSC# C40942](https://lcsc.com/product-detail/USB-Connectors_Jing-Extension-of-the-Electronic-Co-LCSC-micro-5PAll-posts-are-not-guided-Flat-welding-High-temperature_C40942.html)
