### ISSUE TITLE
CM7V-T1A-32.768KHZ-9PF-20PPM-TA-QC

### ISSUE THREAD

**Issue by 8waysanta** [eflukx/OpalSCSI#3]
Hi, this is the last but I'm confused about what LCSC part number you have used in place of the 32.768k crystal at "Y2"

CM7V-T1A-32.768KHZ-9PF-20PPM-TA-QC

Thanks again, Stephen.

**Comment by eflukx** [comment]
This is just a 1.5x3.2mm 32.768kHz crystal. I think any will do. I have this specific part number in it, as I had these in stock.. :)
Moreover I doubt if the BlueSCSI firmware even uses the low speed crystal... If not, the part doesn't need to be placed at all. I haven't tested that though.. Anyone who can shed light on that?

As for LCSC part no., this one will probably do just fine: [Seiko Epson Q13FC1350000400 (LCSC# C32346)](https://lcsc.com/product-detail/Crystals_Seiko-Epson-Q13FC1350000400_C32346.html)

**Comment by eflukx** [comment]
Ps. I'm planning to invest some time to writeup a readme.md and proper BOM. :) (as there seems some interest in this project)

**Comment by rjocoleman** [comment]
> Ps. I'm planning to invest some time to writeup a readme.md and proper BOM. :) (as there seems some interest in this project)

Thanks @eflukx - nice work 😀
